name: Bump and Release
on: workflow_dispatch
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_release_rules: bug:patch:Bug Fixes,Bugfix:patch:Bug Fixes,chore:patch:Chores,feat:minor:Features,Feature:minor:Features,BREAKING:major:Breaking Changes
          create_annotated_tag: true
      - uses: fregante/release-with-changelog@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}